python3 manually_translated_articles_helper.py > manually_translated_articles_helper.tsv
python3 manually_translated_conjunctions_helper.py > manually_translated_conjunctions_helper.tsv
python3 manually_translated_determiners_helper.py > manually_translated_determiners_helper.tsv
python3 manually_translated_interjections_helper.py > manually_translated_interjections_helper.tsv
python3 manually_translated_particles_helper.py > manually_translated_particles_helper.tsv
python3 manually_translated_prepositions_helper.py > manually_translated_prepositions_helper.tsv
python3 manually_translated_pronouns_helper.py > manually_translated_pronouns_helper.tsv
